/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Consumidor;

import kurokami.monitor.Monitor;
import kurokami.monitor.Orden;
import Consumidor.Preparacion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Gilda
 */
public class Consumidorj extends javax.swing.JPanel {

    /**
     * Creates new form Consumidorj
     */
    public Consumidorj(Monitor monitor) {
        initComponents();
        Consumidor c = new Consumidor();
        c.setMonitor(monitor);
        c.start();
        ImageIcon fondo = new ImageIcon("fondos/f1.jpg");
        f.setIcon(fondo);
    }

    /**
     *
     * @author Gilda
     */
    public class Consumidor extends Thread {

        int contador = 0;
        public Monitor monitor;

        public void run() {
            Boolean bandera = true;
            while (bandera == true) {
                Orden cafe;
                cafe = monitor.atenderOrden();
                Preparacion preparacion = new Preparacion(cafe);
                jLabel1.setText(preparacion.getName());
                jLabel2.setText(""+preparacion.Id());
                int tiempo = preparacion.getTiempo();
                int var=0;
                var = tiempo;
                int x = 0;
                while (x < var) {

                    jLabel3.setText(x +"");
                    var = tiempo-x;
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Consumidorj.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    x++;
                }
                x = 0;

            }
        }

        public void setMonitor(Monitor monitor) {
            this.monitor = monitor;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        f = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 180, 30));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 180, 30));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 190, 30));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("PREPARACION DE CAFE");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("ID ORDEN:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("TIPO:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, 20));

        jLabel7.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("TIEMPO RESTANTE:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 170, -1));
        add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(-490, 0, 1070, 830));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel f;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
