/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kurokami.cambioTiempo;
import javax.swing.SpinnerModel;
import kurokami.monitor.TiempoPreparacion;
/**
 *
 * @author marcos
 */
public class CambioTiempo extends javax.swing.JPanel {

    /**
     * Creates new form cambiotiempo
     */
    public CambioTiempo() {
        initComponents();
        this.inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chemex = new javax.swing.JSpinner();
        v60 = new javax.swing.JSpinner();
        expreso = new javax.swing.JSpinner();
        french = new javax.swing.JSpinner();
        moka = new javax.swing.JSpinner();
        late = new javax.swing.JSpinner();
        actualizar = new javax.swing.JButton();
        etiquetaLate = new javax.swing.JLabel();
        etiquetaChemex = new javax.swing.JLabel();
        etiquetaV60 = new javax.swing.JLabel();
        etiqetaExpreso = new javax.swing.JLabel();
        etiquetaFrench = new javax.swing.JLabel();
        etiquetaMoka = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chemex.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        add(chemex, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 390, -1));

        v60.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        add(v60, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 390, -1));

        expreso.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        add(expreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 390, -1));

        french.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        add(french, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 390, -1));

        moka.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        add(moka, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 390, -1));

        late.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        add(late, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 390, -1));

        actualizar.setText("Actualizar Tiempos");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, 270, -1));

        etiquetaLate.setText("Late Frio");
        add(etiquetaLate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 210, 40));

        etiquetaChemex.setText(" Chemex");
        add(etiquetaChemex, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 210, 40));

        etiquetaV60.setText("V60");
        add(etiquetaV60, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 210, 40));

        etiqetaExpreso.setText("Expreso");
        add(etiqetaExpreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 210, 40));

        etiquetaFrench.setText("French Press");
        add(etiquetaFrench, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 210, 40));

        etiquetaMoka.setText("Moka Italiano");
        add(etiquetaMoka, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 210, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        TiempoPreparacion.tiempoChemex = (Integer)chemex.getValue();
        TiempoPreparacion.tiempoExpreso = (Integer)expreso.getValue();
        TiempoPreparacion.tiempoFrench = (Integer)french.getValue();
        TiempoPreparacion.tiempoLate = (Integer)late.getValue();
        TiempoPreparacion.tiempoMoka = (Integer)moka.getValue();
        TiempoPreparacion.tiempoV60 = (Integer)v60.getValue();
    }//GEN-LAST:event_actualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JSpinner chemex;
    private javax.swing.JLabel etiqetaExpreso;
    private javax.swing.JLabel etiquetaChemex;
    private javax.swing.JLabel etiquetaFrench;
    private javax.swing.JLabel etiquetaLate;
    private javax.swing.JLabel etiquetaMoka;
    private javax.swing.JLabel etiquetaV60;
    private javax.swing.JSpinner expreso;
    private javax.swing.JSpinner french;
    private javax.swing.JSpinner late;
    private javax.swing.JSpinner moka;
    private javax.swing.JSpinner v60;
    // End of variables declaration//GEN-END:variables
    private void inicializar(){      
        chemex.setValue(TiempoPreparacion.tiempoChemex);
        expreso.setValue(TiempoPreparacion.tiempoExpreso);
        french.setValue(TiempoPreparacion.tiempoFrench);
        late.setValue(TiempoPreparacion.tiempoLate);
        moka.setValue(TiempoPreparacion.tiempoMoka);
        v60.setValue(TiempoPreparacion.tiempoV60);
        
    }
}
